name: "Build"

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # Also clone recursively to get submodules
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v1
              with:
                  node-version: 14.x
            - run: npm i
            - run: npm run build:prod
            - name: Install firebase packages
              run: |
                cd firebase-js-sdk
                npm i --force
            - name: Build Firebase SDK
              run: |
                ./js-to-lua/dist/apps/convert-js-to-lua/index.js \
                    --input firebase-js-sdk/**/*.js firebase-js-sdk/**/*.ts \
                    --output lua-source-files
