name: "Build"

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # Also clone recursively to get submodules
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v1
              with:
                  node-version: 14.x
            - run: yarn install
            - run: yarn build
