name: "Build"

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # Also clone recursively to get submodules
            - uses: actions/checkout@v3
              with:
                  submodules: recursive
            - uses: actions/setup-node@v1
              with:
                  node-version: 20.x
            - run: |
                cd js-to-lua
                echo Installing js-to-lua...
                npm i
                echo Building...
                npm run build:prod
            - uses: actions/setup-java@v4
              with:
                  distribution: temurin
                  java-version: 17
            - name: Install firebase packages
              run: |
                cd firebase-js-sdk
                yarn set version 1.22.11
                yarn build
            - name: Build Firebase SDK
              run: |
                cd js-to-lua
                ./dist/apps/convert-js-to-lua/index.js \
                    --input firebase-js-sdk/**/*.js firebase-js-sdk/**/*.ts \
                    --output lua-source-files
